import type { SlideElement, Slide } from "./types";

export const initialSlides: Slide[] = [
  { id: "slide-1", title: "1. Giới thiệu CCMG", backgroundColor: "#f8fafc", animation: "fade", minDuration: 4 },
  { id: "slide-2", title: "2. Hướng dẫn Video", backgroundColor: "#ffffff", animation: "slide-up", minDuration: 6 },
  { id: "slide-3", title: "3. Tương tác & Triggers", backgroundColor: "#f0fdf4", animation: "zoom", minDuration: 0 },
  { id: "slide-4", title: "4. Kiểm tra kiến thức", backgroundColor: "#fffbeb", animation: "fade", minDuration: 0 },
  { id: "slide-5", title: "5. Tổng kết", backgroundColor: "#fdf2f8", animation: "fade", minDuration: 0 },
];

export const initialElements: SlideElement[] = [
  // ===== SLIDE 1 =====
  {
    id: "s1-hero",
    slideId: "slide-1",
    type: "card",
    x: 180,
    y: 80,
    width: 600,
    height: 180,
    rotation: 0,
    borderRadius: 24,
    animation: "slide-down",
    props: {
      title: "Chứng chỉ Minh Giám (CCMG) ⭐️",
      body: "Chào mừng sếp đến với Demo tương tác mới. Slide này yêu cầu học viên phải xem ít nhất 4 giây trước khi nút 'Bắt đầu' có thể hoạt động (Tính năng Timelock).",
      titleSize: 26,
      bodySize: 15,
      textColor: "#0f172a",
      backgroundColor: "#e0f2fe",
    },
  },
  {
    id: "s1-start-btn",
    slideId: "slide-1",
    type: "button",
    x: 380,
    y: 320,
    width: 200,
    height: 56,
    rotation: 0,
    borderRadius: 16,
    animation: "zoom",
    props: {
      label: "Bắt đầu học →",
      textColor: "#ffffff",
      backgroundColor: "#2563eb",
      actionType: "go_to_slide",
      targetSlideId: "slide-2",
      buttonSize: 16,
    },
  },

  // ===== SLIDE 2 =====
  {
    id: "s2-title",
    slideId: "slide-2",
    type: "card",
    x: 32,
    y: 32,
    width: 896,
    height: 102,
    rotation: 0,
    borderRadius: 18,
    animation: "fade",
    props: {
      title: "Bài 1: Video Bài Giảng",
      body: "Hệ thống hỗ trợ nhúng Video trực tiếp với tốc độ tải nhanh. Vui lòng xem qua video (Slide này đang khóa 6 giây).",
      titleSize: 22,
      bodySize: 14,
      textColor: "#0f172a",
      backgroundColor: "#fefce8",
    },
  },
  {
    id: "s2-video",
    slideId: "slide-2",
    type: "video",
    x: 230,
    y: 150,
    width: 500,
    height: 280,
    rotation: 0,
    borderRadius: 16,
    animation: "zoom",
    props: {
      videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    },
  },
  {
    id: "s2-next-btn",
    slideId: "slide-2",
    type: "button",
    x: 750,
    y: 430,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "slide-left",
    props: {
      label: "Tiếp theo →",
      textColor: "#ffffff",
      backgroundColor: "#ca8a04",
      actionType: "go_to_slide",
      targetSlideId: "slide-3",
      buttonSize: 15,
    },
  },

  // ===== SLIDE 3 =====
  {
    id: "s3-title",
    slideId: "slide-3",
    type: "card",
    x: 32,
    y: 32,
    width: 896,
    height: 102,
    rotation: 0,
    borderRadius: 18,
    animation: "slide-right",
    props: {
      title: "Tương tác & Hiệu ứng (Animations & Triggers)",
      body: "Thử nhấn nút bên dưới để sử dụng 'Trigger Action' hiển thị một nội dung báo cáo đang bị ẩn (Hidden on Start).",
      titleSize: 20,
      bodySize: 14,
      textColor: "#064e3b",
      backgroundColor: "#d1fae5",
    },
  },
  {
    id: "s3-trigger-btn",
    slideId: "slide-3",
    type: "button",
    x: 32,
    y: 150,
    width: 250,
    height: 56,
    rotation: 0,
    borderRadius: 16,
    animation: "fade",
    props: {
      label: "🔍 Hiện Báo cáo Bí mật",
      textColor: "#ffffff",
      backgroundColor: "#059669",
      actionType: "show_element",
      targetElementIds: ["s3-secret"],
      targetSlideId: "",
      buttonSize: 15,
    },
  },
  {
    id: "s3-secret",
    slideId: "slide-3",
    type: "card",
    name: "Secret Info",
    hidden: true,
    x: 320,
    y: 150,
    width: 600,
    height: 220,
    rotation: 0,
    borderRadius: 20,
    animation: "bounce",
    props: {
      title: "🎉 Nội Dung Tuyệt Mật!",
      body: "Hoàn hảo! Bạn vừa kích hoạt nút ẩn. Phần tử này kết hợp hiệu ứng Bounce In rất mượt mà ngay khoảnh khắc nó xuất hiện lần đầu tiên.",
      titleSize: 24,
      bodySize: 15,
      textColor: "#7f1d1d",
      backgroundColor: "#fecaca",
    },
  },
  {
    id: "s3-next-btn",
    slideId: "slide-3",
    type: "button",
    x: 750,
    y: 430,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    props: {
      label: "Làm bài test →",
      textColor: "#ffffff",
      backgroundColor: "#059669",
      actionType: "go_to_slide",
      targetSlideId: "slide-4",
      buttonSize: 15,
    },
  },

  // ===== SLIDE 4 =====
  {
    id: "s4-title",
    slideId: "slide-4",
    type: "card",
    x: 32,
    y: 24,
    width: 896,
    height: 70,
    rotation: 0,
    borderRadius: 18,
    animation: "fade",
    props: {
      title: "📝 Bài Kiểm Tra Tư Duy",
      body: "Trả lời câu hỏi trắc nghiệm dưới đây (Interactive Quiz Element cung cấp phản hồi Đúng/Sai lập tức).",
      titleSize: 20,
      bodySize: 13,
      textColor: "#1e3a8a",
      backgroundColor: "#dbeafe",
    },
  },
  {
    id: "s4-quiz",
    slideId: "slide-4",
    type: "quiz",
    x: 230,
    y: 120,
    width: 500,
    height: 260,
    rotation: 0,
    borderRadius: 18,
    animation: "slide-up",
    props: {
      title: "Tính năng nào sau đây vừa được bổ sung vào hệ thống ElearnMaker?",
      options: [
        "A. Hỗ trợ hiển thị 3D",
        "B. Thiết lập Slide Timelock & Animations",
        "C. Tích hợp AI tạo content tự động",
        "D. Chế độ nhiều người sửa cùng lúc",
      ],
      correctIndex: 1,
      retryLabel: "Thử lại nhé!",
      titleSize: 15,
      optionSize: 13,
      textColor: "#1e293b",
      backgroundColor: "#ffffff",
    },
  },
  {
    id: "s4-next-btn",
    slideId: "slide-4",
    type: "button",
    x: 750,
    y: 430,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    props: {
      label: "Kết thúc →",
      textColor: "#ffffff",
      backgroundColor: "#1d4ed8",
      actionType: "go_to_slide",
      targetSlideId: "slide-5",
      buttonSize: 15,
    },
  },

  // ===== SLIDE 5 =====
  {
    id: "s5-congrats",
    slideId: "slide-5",
    type: "card",
    x: 180,
    y: 80,
    width: 600,
    height: 150,
    rotation: 0,
    borderRadius: 24,
    animation: "zoom",
    props: {
      title: "🏆 Hoàn Tất Khóa CCMG",
      body: "Sếp đã trải nghiệm đầy đủ các tính năng: Timelock, Animation, Video, Audio, Quiz và Triggers! Hãy dùng thử trình phát Audio cao cấp bên dưới.",
      titleSize: 22,
      bodySize: 14,
      textColor: "#4a044e",
      backgroundColor: "#fae8ff",
    },
  },
  {
    id: "s5-audio",
    slideId: "slide-5",
    type: "audio",
    x: 330,
    y: 260,
    width: 300,
    height: 80,
    rotation: 0,
    borderRadius: 16,
    animation: "slide-up",
    props: {
      audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      autoplay: false,
      loop: true,
      controls: true,
      volume: 0.8,
    },
  },
  {
    id: "s5-restart-btn",
    slideId: "slide-5",
    type: "button",
    x: 380,
    y: 380,
    width: 200,
    height: 50,
    rotation: 0,
    borderRadius: 16,
    animation: "fade",
    props: {
      label: "↺ Xem Lại Từ Đầu",
      textColor: "#ffffff",
      backgroundColor: "#c026d3",
      actionType: "go_to_slide",
      targetSlideId: "slide-1",
      buttonSize: 15,
    },
  },
];

