import type { SlideElement, Slide } from "./types";

export const initialSlides: Slide[] = [
  { id: "slide-home", title: "Trang chủ: Chọn chủ đề", backgroundColor: "#f8fafc", animation: "fade", minDuration: 0 },
  { id: "s1-intro", title: "1.1 Giới thiệu Pháp luật", backgroundColor: "#eff6ff", animation: "slide-right", minDuration: 0 },
  { id: "s1-game-guess", title: "1.2 Game: Đuổi hình bắt chữ", backgroundColor: "#f0f9ff", animation: "zoom", minDuration: 0 },
  { id: "s1-game-match", title: "1.3 Game: Nối cặp đúng nội dung", backgroundColor: "#fdf4ff", animation: "slide-right", minDuration: 0 },
  { id: "s1-quiz", title: "1.4 Trắc nghiệm Quy định", backgroundColor: "#fffbeb", animation: "fade", minDuration: 0 },
  { id: "s1-essay", title: "1.5 Tự luận Pháp lý", backgroundColor: "#f1f5f9", animation: "fade", minDuration: 0 },
  { id: "s1-audio", title: "1.6 Nghe & Trả lời", backgroundColor: "#eff6ff", animation: "fade", minDuration: 0 },
  { id: "s2-intro", title: "2.1 Giới thiệu Đạo đức", backgroundColor: "#f0fdf4", animation: "slide-right", minDuration: 0 },
  { id: "s2-game-guess", title: "2.2 Game: Đuổi hình bắt chữ", backgroundColor: "#f0fdf4", animation: "zoom", minDuration: 0 },
  { id: "s2-game-match", title: "2.3 Game: Nối cặp kỹ năng", backgroundColor: "#fdf4ff", animation: "slide-right", minDuration: 0 },
  { id: "s2-quiz", title: "2.4 Trắc nghiệm Đạo đức", backgroundColor: "#fffbeb", animation: "fade", minDuration: 0 },
  { id: "s2-essay", title: "2.5 Tự luận Xử lý tình huống", backgroundColor: "#f1f5f9", animation: "fade", minDuration: 0 },
  { id: "s2-audio", title: "2.6 Hội thoại mẫu", backgroundColor: "#eff6ff", animation: "fade", minDuration: 0 },
  { id: "s3-intro", title: "3.1 Giới thiệu Thị trường", backgroundColor: "#fff7ed", animation: "slide-right", minDuration: 0 },
  { id: "s3-game-guess", title: "3.2 Game: Đuổi hình bắt chữ", backgroundColor: "#fff7ed", animation: "zoom", minDuration: 0 },
  { id: "s3-game-match", title: "3.3 Game: Nối cặp phân khúc", backgroundColor: "#fdf4ff", animation: "slide-right", minDuration: 0 },
  { id: "s3-quiz", title: "3.4 Trắc nghiệm Chỉ số", backgroundColor: "#fffbeb", animation: "fade", minDuration: 0 },
  { id: "s3-essay", title: "3.5 Tự luận Đánh giá dự án", backgroundColor: "#f1f5f9", animation: "fade", minDuration: 0 },
  { id: "s3-audio", title: "3.6 Tin tức thị trường", backgroundColor: "#eff6ff", animation: "fade", minDuration: 0 },
];

export const initialElements: SlideElement[] = [
  {
    id: "home-title",
    slideId: "slide-home",
    type: "card",
    x: 80,
    y: 60,
    width: 800,
    height: 120,
    rotation: 0,
    borderRadius: 24,
    animation: "slide-down",
    props: {
      title: "CHỨNG CHỈ HÀNH NGHỀ MÔI GIỚI BĐS 🏠",
      body: "Hãy chọn một trong ba chủ đề dưới đây để khám phá kiến thức và nhận chứng chỉ hành nghề chính thức.",
      titleSize: 32,
      bodySize: 16,
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
    },
    zIndex: 2,
  },
  {
    id: "home-btn-1",
    slideId: "slide-home",
    type: "button",
    x: 80,
    y: 220,
    width: 250,
    height: 200,
    rotation: 0,
    borderRadius: 24,
    animation: "zoom",
    props: {
      label: "⚖️\nQuy định & Pháp luật",
      textColor: "#ffffff",
      backgroundColor: "#2563eb",
      actionType: "go_to_slide",
      targetSlideId: "s1-intro",
      buttonSize: 20,
    },
  },
  {
    id: "home-btn-2",
    slideId: "slide-home",
    type: "button",
    x: 355,
    y: 220,
    width: 250,
    height: 200,
    rotation: 0,
    borderRadius: 24,
    animation: "zoom",
    props: {
      label: "🛡️\nKỹ năng & Đạo đức",
      textColor: "#ffffff",
      backgroundColor: "#059669",
      actionType: "go_to_slide",
      targetSlideId: "s2-intro",
      buttonSize: 20,
    },
    zIndex: 1,
  },
  {
    id: "home-btn-3",
    slideId: "slide-home",
    type: "button",
    x: 630,
    y: 220,
    width: 250,
    height: 200,
    rotation: 0,
    borderRadius: 24,
    animation: "zoom",
    props: {
      label: "📈\nThị trường & Đầu tư",
      textColor: "#ffffff",
      backgroundColor: "#d97706",
      actionType: "go_to_slide",
      targetSlideId: "s3-intro",
      buttonSize: 20,
    },
    zIndex: 3,
  },
  {
    id: "s1-intro-card",
    slideId: "s1-intro",
    type: "card",
    x: 100,
    y: 100,
    width: 760,
    height: 300,
    rotation: 0,
    borderRadius: 30,
    animation: "slide-right",
    props: {
      title: "Luật Kinh doanh Bất động sản ⚖️",
      body: "Chủ đề này tập trung vào các quy định mới nhất của Luật Kinh doanh BĐS năm 2023. Đây là nền tảng bắt buộc để mọi môi giới có thể hành nghề an toàn và đúng pháp luật.",
      titleSize: 32,
      bodySize: 18,
      textColor: "#1d4ed8",
      backgroundColor: "#ffffff",
    },
  },
  {
    id: "s1-intro-next",
    slideId: "s1-intro",
    type: "button",
    x: 680,
    y: 472.8570489215914,
    width: 180,
    height: 54,
    rotation: 0,
    borderRadius: 16,
    animation: "fade",
    props: {
      label: "Bắt đầu →",
      textColor: "#ffffff",
      backgroundColor: "#2563eb",
      actionType: "go_to_slide",
      targetSlideId: "s1-game-guess",
      buttonSize: 16,
    },
    zIndex: 15,
  },
  {
    id: "s1-intro-home",
    slideId: "s1-intro",
    type: "button",
    x: 820,
    y: 30,
    width: 110,
    height: 44,
    rotation: 0,
    borderRadius: 12,
    animation: "fade",
    props: {
      label: "🏠 Home",
      textColor: "#1d4ed8",
      backgroundColor: "#ffffff",
      actionType: "go_to_slide",
      targetSlideId: "slide-home",
      buttonSize: 14,
    },
  },
  {
    id: "s1g-game",
    slideId: "s1-game-guess",
    type: "guess_word",
    x: 127.80209294398281,
    y: 4.776668290671591,
    width: 425,
    height: 531,
    rotation: 0,
    borderRadius: 24,
    animation: "zoom",
    props: {
      title: "Thử tài: Đây là ai/cái gì?",
      imageUrls: [
        "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=500&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=500&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=500&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=500&auto=format&fit=crop",
      ],
      answer: "PHAP LUAT",
      hint: "PHAP LUAT",
      successMessage: "Chính xác! Hiểu rõ Pháp luật là yêu cầu tiên quyết của môi giới.",
      titleSize: 24,
      textColor: "#1e3a8a",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s1g-next"],
    },
    zIndex: 13,
  },
  {
    id: "s1g-next",
    slideId: "s1-game-guess",
    type: "button",
    x: 722.0879951008,
    y: 478.13182829608206,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    props: {
      label: "Tiếp tục →",
      textColor: "#ffffff",
      backgroundColor: "#2563eb",
      actionType: "go_to_slide",
      targetSlideId: "s1-game-match",
      buttonSize: 15,
    },
    zIndex: 14,
    hidden: true,
  },
  {
    id: "s1m-game",
    slideId: "s1-game-match",
    type: "matching",
    x: 76.70330389948035,
    y: 13.402984694092488,
    width: 640,
    height: 514,
    rotation: 0,
    borderRadius: 24,
    animation: "slide-up",
    props: {
      title: "Nối loại hình với thời hạn sở hữu 🧩",
      pairs: [
        { id: "p1", left: "Chung cư", right: "50 - 70 năm hoặc Lâu dài" },
        { id: "p2", left: "Đất nền", right: "Sở hữu Lâu dài" },
        { id: "p3", left: "Condotel", right: "50 năm (Đất TMDV)" },
        { id: "p4", left: "Shophouse khối đế", right: "Theo thời hạn dự án" },
      ],
      titleSize: 22,
      itemSize: 16,
      textColor: "#1e3a8a",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s1m-next"],
    },
    zIndex: 11,
  },
  {
    id: "s1m-next",
    slideId: "s1-game-match",
    type: "button",
    x: 763.2966961005196,
    y: 479.6702646479008,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    props: {
      label: "Làm Quiz →",
      textColor: "#ffffff",
      backgroundColor: "#10b981",
      actionType: "go_to_slide",
      targetSlideId: "s1-quiz",
      buttonSize: 15,
    },
    zIndex: 10,
    hidden: true,
  },
  {
    id: "s1q-quiz",
    slideId: "s1-quiz",
    type: "quiz",
    x: 180,
    y: 60,
    width: 564,
    height: 400,
    rotation: 0,
    borderRadius: 24,
    animation: "zoom",
    props: {
      title: "Cá nhân hành nghề môi giới BĐS phải có chứng chỉ hành nghề và làm việc tại đâu?",
      options: [
        "A. Làm việc tự do (Freelance) không cần đăng ký",
        "B. Làm việc tại doanh nghiệp kinh doanh dịch vụ sàn giao dịch BĐS hoặc môi giới BĐS",
        "C. Chỉ cần có văn phòng tại nhà riêng",
        "D. Làm việc trực tiếp với chủ đầu tư mà không cần pháp nhân",
      ],
      correctIndex: 1,
      retryLabel: "Đọc kỹ Luật 2023 nhé!",
      titleSize: 20,
      optionSize: 14,
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s1q-next"],
    },
    zIndex: 16,
  },
  {
    id: "s1q-next",
    slideId: "s1-quiz",
    type: "button",
    x: 760,
    y: 476.4834803742102,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    props: {
      label: "Viết Tự luận →",
      textColor: "#ffffff",
      backgroundColor: "#0ea5e9",
      actionType: "go_to_slide",
      targetSlideId: "s1-essay",
      buttonSize: 15,
    },
    zIndex: 17,
    hidden: true,
  },
  {
    id: "s1e-essay",
    slideId: "s1-essay",
    type: "essay",
    x: 100,
    y: 40.74179771170409,
    width: 760,
    height: 411,
    rotation: 0,
    borderRadius: 24,
    animation: "slide-down",
    props: {
      title: "Theo bạn, thay đổi lớn nhất về quy định hành nghề môi giới trong Luật 2023 là gì?",
      placeholder: "Nhập suy nghĩ của bạn (Ví dụ: Việc bắt buộc hành nghề tại doanh nghiệp...)",
      submitLabel: "Nộp bài phân tích",
      minLength: 50,
      maxLength: 1000,
      titleSize: 20,
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
    },
    zIndex: 18,
  },
  {
    id: "s1e-next",
    slideId: "s1-essay",
    type: "button",
    x: 760,
    y: 481.4285243966017,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    props: {
      label: "Nghe & Trả lời →",
      textColor: "#ffffff",
      backgroundColor: "#f59e0b",
      actionType: "go_to_slide",
      targetSlideId: "s1-audio",
      buttonSize: 15,
    },
    zIndex: 19,
  },
  {
    id: "s1a-audio",
    slideId: "s1-audio",
    type: "audio",
    x: 343.1867842736906,
    y: 33.84625497788898,
    width: 300,
    height: 100,
    rotation: 0,
    borderRadius: 50,
    animation: "zoom",
    props: {
      audioUrl: "/uploads/demo_voice.mp3",
      autoplay: true,
      loop: false,
      controls: true,
      volume: 0.8,
      actionType: "show_element",
      targetElementIds: ["s1a-quiz"],
    },
    zIndex: 25,
    hidden: true,
  },
  {
    id: "s1a-quiz",
    slideId: "s1-audio",
    type: "quiz",
    x: 204.175661619752,
    y: 149.56420615272384,
    width: 568,
    height: 298,
    rotation: 0,
    borderRadius: 20,
    animation: "fade",
    props: {
      title: "Dựa vào đoạn âm thanh trên, đối tượng nào được phép cấp chứng chỉ môi giới?",
      options: [
        "A. Sở Xây dựng các tỉnh, thành phố",
        "B. Các sàn giao dịch tự cấp",
        "C. Hội môi giới BĐS Việt Nam",
        "D. Ủy ban nhân dân cấp xã",
      ],
      correctIndex: 0,
      retryLabel: "Nghe lại đoạn băng nhé!",
      titleSize: 18,
      optionSize: 14,
      textColor: "#1d4ed8",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s1a-home"],
    },
    zIndex: 23,
    hidden: true,
  },
  {
    id: "s1a-home",
    slideId: "s1-audio",
    type: "button",
    x: 411.5384362234307,
    y: 478.13182842447003,
    width: 160,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "bounce",
    hidden: true,
    props: {
      label: "Xong! Về Menu",
      textColor: "#ffffff",
      backgroundColor: "#1d4ed8",
      actionType: "go_to_slide",
      targetSlideId: "slide-home",
      buttonSize: 15,
    },
    zIndex: 26,
  },
  {
    id: "s2-intro-card",
    slideId: "s2-intro",
    type: "card",
    x: 100,
    y: 100,
    width: 760,
    height: 300,
    rotation: 0,
    borderRadius: 30,
    animation: "slide-right",
    props: {
      title: "Đạo đức & Kỹ năng hành nghề 🛡️",
      body: "Môi giới không chỉ là bán hàng, đó là nghề tư vấn dựa trên sự tin cậy. Chương này giúp bạn xây dựng bộ quy tắc đạo đức và kỹ năng đàm phán chuyên nghiệp.",
      titleSize: 32,
      bodySize: 18,
      textColor: "#047857",
      backgroundColor: "#ffffff",
    },
  },
  {
    id: "s2-intro-next",
    slideId: "s2-intro",
    type: "button",
    x: 691.5384362234307,
    y: 474.5053969718512,
    width: 180,
    height: 54,
    rotation: 0,
    borderRadius: 16,
    animation: "fade",
    props: {
      label: "Bắt đầu →",
      textColor: "#ffffff",
      backgroundColor: "#059669",
      actionType: "go_to_slide",
      targetSlideId: "s2-game-guess",
      buttonSize: 16,
    },
    zIndex: 27,
  },
  {
    id: "s2g-game",
    slideId: "s2-game-guess",
    type: "guess_word",
    x: 262.9666317814082,
    y: 3.9561668047180554,
    width: 494,
    height: 483,
    rotation: 0,
    borderRadius: 24,
    animation: "zoom",
    props: {
      title: "Phẩm chất quan trọng nhất?",
      imageUrls: [
        "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=500&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=500&auto=format&fit=crop",
      ],
      answer: "TRUNG THUC",
      hint: "TRUNG THUC",
      successMessage: "Đúng vậy! Trung thực là giá trị cốt lõi của nghề môi giới.",
      titleSize: 24,
      textColor: "#064e3b",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s2g-next"],
    },
    zIndex: 55,
  },
  {
    id: "s2g-next",
    slideId: "s2-game-guess",
    type: "button",
    x: 760,
    y: 481.4285243966017,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    hidden: true,
    props: {
      label: "Tiếp tục →",
      textColor: "#ffffff",
      backgroundColor: "#059669",
      actionType: "go_to_slide",
      targetSlideId: "s2-game-match",
      buttonSize: 15,
    },
    zIndex: 28,
  },
  {
    id: "s2m-game",
    slideId: "s2-game-match",
    type: "matching",
    x: 80,
    y: 31.012838932128574,
    width: 800,
    height: 414,
    rotation: 0,
    borderRadius: 24,
    animation: "slide-up",
    props: {
      title: "Phân loại kỹ năng môi giới 🛠️",
      pairs: [
        { id: "m1", left: "Giao tiếp", right: "Lắng nghe & thấu hiểu nhu cầu" },
        { id: "m2", left: "Đàm phán", right: "Tìm điểm chung giữa người mua-bán" },
        { id: "m3", left: "Pháp lý", right: "Kiểm tra sổ đỏ, quy hoạch" },
        { id: "m4", left: "Marketing", right: "Tìm kiếm khách hàng tiềm năng" },
      ],
      titleSize: 22,
      itemSize: 16,
      textColor: "#065f46",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s2m-next"],
    },
    zIndex: 31,
  },
  {
    id: "s2m-next",
    slideId: "s2-game-match",
    type: "button",
    x: 761.6483480502599,
    y: 474.7252204971213,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    hidden: true,
    props: {
      label: "Làm Quiz →",
      textColor: "#ffffff",
      backgroundColor: "#10b981",
      actionType: "go_to_slide",
      targetSlideId: "s2-quiz",
      buttonSize: 15,
    },
    zIndex: 32,
  },
  {
    id: "s2-quiz-el",
    slideId: "s2-quiz",
    type: "quiz",
    x: 196.48348037421022,
    y: 63.29669610051965,
    width: 587,
    height: 400,
    rotation: 0,
    borderRadius: 24,
    animation: "zoom",
    props: {
      title: "Hành vi nào sau đây vi phạm đạo đức hành nghề môi giới?",
      options: [
        "A. Cung cấp thông tin quy hoạch chính xác",
        "B. Tư vấn khách hàng về rủi ro tài chính",
        "C. Nâng giá bán so với giá chủ nhà đưa ra để hưởng chênh lệch (Kê giá)",
        "D. Giải thích kỹ các điều khoản hợp đồng cọc",
      ],
      correctIndex: 2,
      retryLabel: "Xem lại bộ quy tắc đạo đức nhé!",
      titleSize: 20,
      optionSize: 14,
      textColor: "#064e3b",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s2-quiz-next"],
    },
    zIndex: 34,
  },
  {
    id: "s2-quiz-next",
    slideId: "s2-quiz",
    type: "button",
    x: 761.6483480502599,
    y: 478.13182842447003,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    hidden: true,
    props: {
      label: "Xử lý tình huống →",
      textColor: "#ffffff",
      backgroundColor: "#059669",
      actionType: "go_to_slide",
      targetSlideId: "s2-essay",
      buttonSize: 15,
    },
    zIndex: 33,
  },
  {
    id: "s2-essay-el",
    slideId: "s2-essay",
    type: "essay",
    x: 100,
    y: 60,
    width: 760,
    height: 380,
    rotation: 0,
    borderRadius: 24,
    animation: "slide-down",
    props: {
      title: "Nếu khách hàng muốn bạn che giấu thông tin lỗi phong thủy để dễ bán, bạn sẽ làm gì?",
      placeholder: "Nhập cách xử lý của bạn...",
      submitLabel: "Gửi phương án xử lý",
      minLength: 30,
      maxLength: 1000,
      titleSize: 20,
      textColor: "#064e3b",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s2-essay-next"],
    },
    zIndex: 53,
  },
  {
    id: "s2-essay-next",
    slideId: "s2-essay",
    type: "button",
    x: 760,
    y: 478.13182842447003,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    hidden: true,
    props: {
      label: "Audio Test →",
      textColor: "#ffffff",
      backgroundColor: "#059669",
      actionType: "go_to_slide",
      targetSlideId: "s2-audio",
      buttonSize: 15,
    },
    zIndex: 35,
  },
  {
    id: "s2-audio-player",
    slideId: "s2-audio",
    type: "audio",
    x: 331.6483480502598,
    y: 48.68138730183938,
    width: 300,
    height: 100,
    rotation: 0,
    borderRadius: 50,
    animation: "zoom",
    hidden: true,
    props: {
      audioUrl: "/uploads/demo_voice.mp3",
      autoplay: true,
      loop: false,
      controls: true,
      volume: 0.8,
      actionType: "show_element",
      targetElementIds: ["s2-audio-quiz"],
    },
    zIndex: 37,
  },
  {
    id: "s2-audio-quiz",
    slideId: "s2-audio",
    type: "quiz",
    x: 184.46142561482128,
    y: 158.21986962198213,
    width: 605,
    height: 296,
    rotation: 0,
    borderRadius: 20,
    animation: "fade",
    hidden: true,
    props: {
      title: "Trong cuộc hội thoại này, kỹ năng nào đang được môi giới sử dụng tốt nhất?",
      options: ["A. Ép khách chốt cọc", "B. Lắng nghe chủ động", "C. Thao túng tâm lý", "D. Bỏ qua câu hỏi của khách"],
      correctIndex: 1,
      retryLabel: "Lắng nghe kỹ hơn nhé!",
      titleSize: 18,
      optionSize: 14,
      textColor: "#047857",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s2-audio-home"],
    },
    zIndex: 39,
  },
  {
    id: "s2-audio-home",
    slideId: "s2-audio",
    type: "button",
    x: 404.9450441507795,
    y: 481.4285243966017,
    width: 160,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "bounce",
    hidden: true,
    props: {
      label: "Về Menu chính",
      textColor: "#ffffff",
      backgroundColor: "#059669",
      actionType: "go_to_slide",
      targetSlideId: "slide-home",
      buttonSize: 15,
    },
    zIndex: 40,
  },
  {
    id: "s3-intro-card",
    slideId: "s3-intro",
    type: "card",
    x: 100,
    y: 100,
    width: 760,
    height: 300,
    rotation: 0,
    borderRadius: 30,
    animation: "slide-right",
    props: {
      title: "Thị trường & Phân tích Đầu tư 📈",
      body: "Làm sao để biết thời điểm nào nên mua vào hay bán ra? Chương này cung cấp các chỉ số vĩ mô và kỹ năng đánh giá dự án thực chiến.",
      titleSize: 32,
      bodySize: 18,
      textColor: "#b45309",
      backgroundColor: "#ffffff",
    },
  },
  {
    id: "s3-intro-next",
    slideId: "s3-intro",
    type: "button",
    x: 680,
    y: 472.8570489215914,
    width: 180,
    height: 54,
    rotation: 0,
    borderRadius: 16,
    animation: "fade",
    props: {
      label: "Bắt đầu →",
      textColor: "#ffffff",
      backgroundColor: "#d97706",
      actionType: "go_to_slide",
      targetSlideId: "s3-game-guess",
      buttonSize: 16,
    },
    zIndex: 41,
  },
  {
    id: "s3g-game",
    slideId: "s3-game-guess",
    type: "guess_word",
    x: 144.2855733181931,
    y: 10.152120808956992,
    width: 459,
    height: 519,
    rotation: 0,
    borderRadius: 24,
    animation: "zoom",
    props: {
      title: "Nơi diễn ra giao dịch?",
      imageUrls: [
        "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1543286386-713bdd548da4?w=500&auto=format&fit=crop",
      ],
      answer: "THI TRUONG",
      hint: "THI TRUONG",
      successMessage: "Tuyệt vời! Hiểu thị trường là nắm chắc 50% thành công.",
      titleSize: 24,
      textColor: "#78350f",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s3g-next"],
    },
    zIndex: 44,
  },
  {
    id: "s3g-next",
    slideId: "s3-game-guess",
    type: "button",
    x: 760,
    y: 483.0768724468615,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    hidden: true,
    props: {
      label: "Nối phân khúc →",
      textColor: "#ffffff",
      backgroundColor: "#d97706",
      actionType: "go_to_slide",
      targetSlideId: "s3-game-match",
      buttonSize: 15,
    },
    zIndex: 42,
  },
  {
    id: "s3m-game",
    slideId: "s3-game-match",
    type: "matching",
    x: 78.35165194974017,
    y: 21.868171575529953,
    width: 800,
    height: 440,
    rotation: 0,
    borderRadius: 24,
    animation: "slide-up",
    props: {
      title: "Phân khúc BĐS và đặc điểm 🧩",
      pairs: [
        { id: "v1", left: "Nhà phố", right: "Giá trị cao, tính thanh khoản tốt" },
        { id: "v2", left: "Căn hộ", right: "Phù hợp cho thuê, dòng tiền ổn định" },
        { id: "v3", left: "Đất nền", right: "Kỳ vọng tăng giá mạnh, rủi ro pháp lý" },
        { id: "v4", left: "Nghỉ dưỡng", right: "Ảnh hưởng bởi du lịch và hạ tầng" },
      ],
      titleSize: 22,
      itemSize: 16,
      textColor: "#92400e",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s3m-next"],
    },
    zIndex: 47,
  },
  {
    id: "s3m-next",
    slideId: "s3-game-match",
    type: "button",
    x: 760,
    y: 482.96696074842043,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    hidden: true,
    props: {
      label: "Làm Quiz →",
      textColor: "#ffffff",
      backgroundColor: "#d97706",
      actionType: "go_to_slide",
      targetSlideId: "s3-quiz",
      buttonSize: 15,
    },
    zIndex: 46,
  },
  {
    id: "s3q-quiz",
    slideId: "s3-quiz",
    type: "quiz",
    x: 180,
    y: 60,
    width: 600,
    height: 400,
    rotation: 0,
    borderRadius: 24,
    animation: "zoom",
    props: {
      title: "Chỉ số nào sau đây phản ánh sức ảnh hưởng của lạm phát đến BĐS?",
      options: [
        "A. Chỉ số hài lòng khách hàng",
        "B. Tỷ lệ tăng trưởng số lượng môi giới",
        "C. Chỉ số giá tiêu dùng (CPI)",
        "D. Số lượng tin đăng bán trên mạng",
      ],
      correctIndex: 2,
      retryLabel: "Kiến thức vĩ mô này rất quan trọng!",
      titleSize: 20,
      optionSize: 14,
      textColor: "#78350f",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s3q-next"],
    },
    hidden: false,
  },
  {
    id: "s3q-next",
    slideId: "s3-quiz",
    type: "button",
    x: 758.3516519497401,
    y: 479.78017647472984,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    hidden: true,
    props: {
      label: "Tự luận →",
      textColor: "#ffffff",
      backgroundColor: "#d97706",
      actionType: "go_to_slide",
      targetSlideId: "s3-essay",
      buttonSize: 15,
    },
    zIndex: 48,
  },
  {
    id: "s3e-essay",
    slideId: "s3-essay",
    type: "essay",
    x: 100,
    y: 60,
    width: 760,
    height: 380,
    rotation: 0,
    borderRadius: 24,
    animation: "slide-down",
    props: {
      title: "Hãy nêu 3 yếu tố quan trọng nhất khi đánh giá tiềm năng tăng giá của một dự án BĐS?",
      placeholder: "VD: Vị trí, Hạ tầng, Pháp lý...",
      submitLabel: "Gửi đánh giá",
      minLength: 30,
      maxLength: 1000,
      titleSize: 20,
      textColor: "#78350f",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s3e-next"],
    },
    zIndex: 53,
  },
  {
    id: "s3e-next",
    slideId: "s3-essay",
    type: "button",
    x: 760,
    y: 481.4285243966017,
    width: 170,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "fade",
    hidden: true,
    props: {
      label: "Nghe tin tức →",
      textColor: "#ffffff",
      backgroundColor: "#d97706",
      actionType: "go_to_slide",
      targetSlideId: "s3-audio",
      buttonSize: 15,
    },
    zIndex: 49,
  },
  {
    id: "s3a-audio",
    slideId: "s3-audio",
    type: "audio",
    x: 338.2417402512991,
    y: 37.14295107840863,
    width: 300,
    height: 100,
    rotation: 0,
    borderRadius: 50,
    animation: "zoom",
    hidden: true,
    props: {
      audioUrl: "/uploads/demo_voice.mp3",
      autoplay: true,
      loop: false,
      controls: true,
      volume: 0.8,
      actionType: "show_element",
      targetElementIds: ["s3a-quiz"],
    },
    zIndex: 58,
  },
  {
    id: "s3a-quiz",
    slideId: "s3-audio",
    type: "quiz",
    x: 130,
    y: 167.90299618617348,
    width: 700,
    height: 282,
    rotation: 0,
    borderRadius: 20,
    animation: "fade",
    hidden: true,
    props: {
      title: "Tin tức vừa nghe dự báo xu hướng thị trường nào trong 6 tháng tới?",
      options: ["A. Tăng trưởng nóng", "B. Đóng băng hoàn toàn", "C. Phục hồi chậm, tập trung nhu cầu thực", "D. Chỉ số chứng khoán giảm mạnh"],
      correctIndex: 2,
      retryLabel: "Tin tức này rất quan trọng!",
      titleSize: 18,
      optionSize: 14,
      textColor: "#92400e",
      backgroundColor: "#ffffff",
      actionType: "show_element",
      targetElementIds: ["s3a-home"],
    },
    zIndex: 59,
  },
  {
    id: "s3a-home",
    slideId: "s3-audio",
    type: "button",
    x: 401.6483480502598,
    y: 474.83513232395035,
    width: 160,
    height: 50,
    rotation: 0,
    borderRadius: 14,
    animation: "bounce",
    hidden: true,
    props: {
      label: "Hoàn tất khóa học",
      textColor: "#ffffff",
      backgroundColor: "#d97706",
      actionType: "go_to_slide",
      targetSlideId: "slide-home",
      buttonSize: 15,
    },
    zIndex: 52,
  },
];
